server.port=8080

# Oracle — valores lidos de variáveis de ambiente (docker-compose injeta)
spring.datasource.url=${ORACLE_URL:jdbc:oracle:thin:@localhost:1521:XE}
spring.datasource.username=${ORACLE_USER:hackgov}
spring.datasource.password=${ORACLE_PASS:hackgov123}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

logging.level.br.com.hackgov=INFO
